language: node_js

node_js:
  - node

dist: trusty

if: type = pull_request OR branch = master OR tag IS present

cache:
  npm: true

script:
  - echo "Script !"

deploy:
  - provider: script
    script: echo 'Deploy 1'
    on:
      tags: true
